### ISSUE TITLE
CLI version doesn't seem to sort the given file (since v1.4.1)

### ISSUE THREAD

**Issue by matatk** [kesla/sort-json#11]
Thanks for this tool. I have been using it for a while, and got the same error as reported in #10. I then updated to 1.4.1, but now the JSON file I was trying to sort is not actually sorted anymore.  There are no error messages and `sort-json` returns a 0 exit code, but the file doesn't appear to be touched.

**Comment by KhaledMohamedP** [comment]
Please provide a sample file and would look into this issue with you? also it will help if you share your env?

**Comment by matatk** [comment]
At the moment, I can't access the machine where I was having this problem, but I just installed the latest version on a different machine and it's working fine.  I suspect this means the problem was something to do with my set-up; sorry.

**Comment by kesla** [comment]
please reopen if this is still an issue
