### ISSUE TITLE
npm install - failed because cmd.js file not found

### ISSUE THREAD

**Issue by alexandrehebert** [kesla/sort-json#16]
https://github.com/kesla/sort-json/blob/dcd53805ef556fa5f1d1946e678521d96d577f58/package.json#L10

The file cmd.js is not in the root folder, so the install command failed when npm is trying to change the permissions in order to execute it.

I'm using Node 6.6.0. Npm 5.4.2.

**Comment by genru** [comment]
same problem

**Comment by spi7fire** [comment]
Same here,
im getting this error:
pm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "--save" "gulp-chrome-manifest"
npm ERR! node v8.4.0
npm ERR! npm v3.10.10
npm ERR! path /data/projects/test/node_modules/sort-json/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/data/projects/test/node_modules/sort-json/cmd.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/data/projects/test/node_modules/sort-json/cmd.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR! /data/projects/test/npm-debug.log

**Comment by kesla** [comment]
Fixed by #17 and pushed in 1.5.1
