### ISSUE TITLE
Detect and respect indentation

### ISSUE THREAD

**Issue by hubbergit** [kesla/sort-json#21]
sort-json uses an indentation of 2 spaces. However one may have chosen to use another indentation level (for example 4 spaces) or tabs instead of spaces. Either this should be configurable or should be detected automatically.

**Comment by kesla** [comment]
@hubbergit that sound like a great idea, I'd gladly accept a PR!

**Comment by cschuller** [comment]
@kesla This issue can now be closed. :-)

**Comment by hubbergit** [comment]
Thanks @cschuller and @kesla for the new possibility to respect the indentation.

Only one minor comment: My initial comment also mentioned that one might have chosen to use tabs instead of spaces. That one is not solved, but if someone needs a solution for that, a new issue should be opened.

**Comment by kesla** [comment]
@hubbergit Looks like detect-indent can identify tabs, so I _think_ it'll work with tabs. Haven't tested it however.

**Comment by hubbergit** [comment]
@kesla I can confirm that it works with tabs as well.

Both thumbs up.
