### ISSUE TITLE
Cannot locate license type for the library

### ISSUE THREAD

**Issue by dwmoore** [kesla/sort-json#35]
Hi! First up, thanks for all the hard work on this project. Maintainers don't receive near enough props for all they do. Good on you, fine folk!

We are making use of sort-json in our product and as part of our dependency audit, we were unable to locate a license for its use.

I would not want to presume anyone's intent with regards to free distribution of their work, but I also don't want to open an issue without providing some form of solution to the problem. In light of this, might I suggest the MIT license? It is a common choice to allow permissive use and popular for open source software. You can find examples in many common repositories, such as React: https://github.com/facebook/react/blob/master/LICENSE

Other, less common options include BSD 2 and 3 clause, Creative Commons, and of course all rights may be reserved.

Thanks again and please let me know if I may provide any additional help. My hope is that this will be a quick and easy change, but I'm happy to open a PR with the specified license if you let me know the preference.

Cheers!

**Comment by kesla** [comment]
I have defined the license in the package.json but I've added a `LICENSE` file as well in the repo. Lmk if something's missing for you!

**Comment by dwmoore** [comment]
You are awesome! Thank you!
