### ISSUE TITLE
should not change number formats

### ISSUE THREAD

**Issue by mfulton26** [kesla/sort-json#42]
input:

```json
{
  "number": 1e10
}
```

expected:

```json
{
  "number": 1e10
}
```

actual:

```json
{
  "number": 10000000000
}
```

**Comment by kesla** [comment]
The number format is only how it's shown in Node.js, it doesn't have anything to do with how this module works.

Even if I write just `const a = 1e10` it'll then be written out as `10000000000`.

So this isn't a bug but how Node.js handles numbers :)

**Comment by mfulton26** [comment]
Hmmm, that's to bad. My group can't use this library if it changes the values in the JSON document.

**Comment by kesla** [comment]
@mfulton26 but it does not change the values. The value in 1e10 is 10000000000, independently on how it is written out for you.

**Comment by mfulton26** [comment]
I said "values" but what I really should have said is "literals". JSON supports `1e10`, `1e+10`, `1E10`, etc. and we need those literals retained when sorting a JSON document and left untouched.
